### ISSUE TITLE
请问怎样测试单幅或多幅自己的图像质量？

### ISSUE THREAD

**Issue by weidelongdongqiang** [zwx8981/UNIQUE#1]
怎样调用训练好的模型测试单幅或多幅自己的图像质量？貌似并没有可用的模型文件

**Comment by zwx8981** [comment]
你好，我们暂时没有放出训练好的权重，不好意思，如果在训练过程中有任何问题非常乐意解答



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weidelongdongqiang <notifications@github.com&gt;
发送时间: 2020年9月5日 17:11
收件人: zwx8981/UNIQUE <UNIQUE@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[zwx8981/UNIQUE] 请问怎样测试单幅或多幅自己的图像质量？ (#1)





 
怎样调用训练好的模型测试单幅或多幅自己的图像质量？貌似并没有可用的模型文件

**Comment by zwx8981** [comment]
@weidelongdongqiang 我们放出了一个模型文件，如果还需要的话可以下载
