### ISSUE TITLE
Could you share me the result from matlab?

### ISSUE THREAD

**Issue by ciwei123** [zwx8981/UNIQUE#11]
@zwx8981 Thanks for your sharing. I want to train the dataset, but I have no matlab, Could you share me the result from `data_all.m` . Thank you very much!!

**Comment by zwx8981** [comment]
@ciwei123 ，You can find the files here:
https://drive.google.com/file/d/1u-6xmedUB0PNA5xM787OY-YfiJg195xA/view?usp=sharing

**Comment by ciwei123** [comment]
> @ciwei123 ，You can find the files here:
> https://drive.google.com/file/d/1u-6xmedUB0PNA5xM787OY-YfiJg195xA/view?usp=sharing

@zwx8981 Thanks for your reply. But I can not access the link, Could you share by Baidudisk? or `https://console.cloud.google.com `?

**Comment by zwx8981** [comment]
@ciwei123 
链接: https://pan.baidu.com/s/12nb6OTUxnz_rxssg2rthIQ  密码: 82k3
