### ISSUE TITLE
About the dataset that is lack of the variance data

### ISSUE THREAD

**Issue by SuperCrystal** [zwx8981/UNIQUE#12]
Hello, the model seems work very well on dataset such as tid2013, koniq10k etc. But there is a problem that what if the variance of MOS data is unknown?

**Comment by zwx8981** [comment]
@SuperCrystal Hi, thank you for your interest. If the variance of MOS data is unknown, you can just use the binary labels to train the model.

**Comment by SuperCrystal** [comment]
> @SuperCrystal Hi, thank you for your interest. If the variance of MOS data is unknown, you can just use the binary labels to train the model.

Thanks a lot. The binary labels seem work fine to me:)
