### ISSUE TITLE
About the mean output

### ISSUE THREAD

**Issue by liujianzhao6328057** [zwx8981/UNIQUE#14]
Hi, thanks for your significant work. In this work. a softplus function is applied to the std output. However, there is no constrains to 
 the mean output.  Does the performance will be influenced  If a sigmoid function is applied to the mean output?

**Comment by zwx8981** [comment]
@liujianzhao6328057 I had tried uisng a sigmoid function to the mean ouput, which makes the optimization more diffcult, leading to significant performance drop.
