### ISSUE TITLE
How are the cross-dataset experiments conducted?

### ISSUE THREAD

**Issue by yunchengwang** [zwx8981/UNIQUE#18]
Hi, 

Thank you so much for the amazing work! I have a question regarding Table IV in the original paper.

In the table, baseline models are trained with some datasets and tested on the other datasets. How are the cross-dataset experiments conducted given that the MOS/DMOS ranges are different across datasets? Do you re-train the FC layers for each dataset during testing? Thanks.

**Comment by zwx8981** [comment]
Hi, thanks for your interest. 

In cross-dataset experiments, we don't need to re-train FC layers for each dataset during testing. We directly use the models trained on other datasets to test on target datasets. The difference of ranges won't affect the results, you can still compute the SRCC/PLCC between yor model predictions and the gound-truth MOS/DMOS.
