### ISSUE TITLE
Model validation

### ISSUE THREAD

**Issue by zhj1ein** [zwx8981/UNIQUE#2]
Thanks for your great job!
Did you use validation data to obtain the best checkpoint (model)?

**Comment by zwx8981** [comment]
@pencilzhang Hi, thank you for appreciating our work. We follow the practice of most BIQA papers to split the training/testing test by an 80%/20% ratio. So, there is no data reserved for validation. For a more strict evaluation without referring to the results on test sets, we can always use the latest checkpoints for evaluation, although we see no big difference between both strategies.

**Comment by zhj1ein** [comment]
@zwx8981  Thanks for your response!
