### ISSUE TITLE
bilinear pooling layer

### ISSUE THREAD

**Issue by zhj1ein** [zwx8981/UNIQUE#6]
Hi, 
you proposed to use bilinear pooling instead of first-order average pooling in the original resnet, as mentioned in the paper.
However, I found the average pooling is kept in the implementation of resnet (BaseCNN.py). A bilinear pooling layer is added on top of that, no?

**Comment by zwx8981** [comment]
Yes, I didn't remove the original 1000-dim fc layer. But it will not be updated during the training and has no effect on the testing.
