### ISSUE TITLE
about the BID datasets

### ISSUE THREAD

**Issue by liujianzhao6328057** [zwx8981/UNIQUE#8]
Thanks for your great job! Could you please provide a download link for BID dataset? I cannot find it on the internet. Thanks very much

**Comment by zwx8981** [comment]
@liujianzhao6328057  You can find it here.

https://pan.baidu.com/s/1To2an2_Cu3yPvnTiCMOrsQ 
code：gkk5

**Comment by ZhiliangMa-lang** [comment]
Could you please provide a download link for BID dataset again？The above link is broken.Thanks

**Comment by zwx8981** [comment]
@ZhiliangMa-lang  
https://pan.baidu.com/s/1BEzeDcQfPab1xokw71nOcQ 
code：78e9
